using System.Text.Json;
using Lifeblood.Application.Ports.Infrastructure;
using Lifeblood.Application.Ports.Left;
using Microsoft.CodeAnalysis;

namespace Lifeblood.Adapters.CSharp.Internal;

/// <summary>
/// Resolves NuGet package assemblies from obj/project.assets.json.
/// This file is generated by 'dotnet restore' and maps each package to its compile-time DLLs.
/// Falls back gracefully if the file doesn't exist (pre-restore state).
/// </summary>
internal sealed class NuGetReferenceResolver
{
    private readonly IFileSystem _fs;

    public NuGetReferenceResolver(IFileSystem fs) => _fs = fs;

    /// <summary>
    /// Resolve NuGet references for a module, deduplicating via shared cache.
    /// Without the cache, 100 modules sharing the same NuGet packages create
    /// 100 independent MetadataReference objects per shared DLL.
    /// </summary>
    public MetadataReference[] Resolve(ModuleInfo module, string projectRoot,
        SharedMetadataReferenceCache? cache = null)
    {
        if (!module.Properties.TryGetValue("projectFile", out var relCsproj))
            return Array.Empty<MetadataReference>();

        var csprojPath = Path.GetFullPath(Path.Combine(projectRoot, relCsproj));
        var objDir = Path.Combine(Path.GetDirectoryName(csprojPath)!, "obj");
        var assetsPath = Path.Combine(objDir, "project.assets.json");

        if (!_fs.FileExists(assetsPath))
            return Array.Empty<MetadataReference>();

        try
        {
            var json = _fs.ReadAllText(assetsPath);
            using var doc = JsonDocument.Parse(json);

            var packageFolders = new List<string>();
            if (doc.RootElement.TryGetProperty("packageFolders", out var folders))
            {
                foreach (var folder in folders.EnumerateObject())
                    packageFolders.Add(folder.Name);
            }

            if (packageFolders.Count == 0)
                return Array.Empty<MetadataReference>();

            if (!doc.RootElement.TryGetProperty("targets", out var targets))
                return Array.Empty<MetadataReference>();

            JsonElement targetPackages = default;
            foreach (var target in targets.EnumerateObject())
            {
                targetPackages = target.Value;
                break; // Use first target framework
            }

            if (targetPackages.ValueKind != JsonValueKind.Object)
                return Array.Empty<MetadataReference>();

            var references = new List<MetadataReference>();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var package in targetPackages.EnumerateObject())
            {
                if (!package.Value.TryGetProperty("compile", out var compileAssets))
                    continue;

                var pkgId = package.Name;

                foreach (var asset in compileAssets.EnumerateObject())
                {
                    var relativeDll = asset.Name;
                    if (relativeDll == "_._") continue;
                    if (!relativeDll.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)) continue;

                    foreach (var folder in packageFolders)
                    {
                        var dllPath = Path.Combine(folder, pkgId.ToLowerInvariant(), relativeDll);
                        if (!seen.Add(dllPath)) continue;

                        if (_fs.FileExists(dllPath) && !BclReferenceLoader.IsNativeDll(dllPath))
                        {
                            try
                            {
                                var reference = cache != null
                                    ? cache.GetOrCreate(dllPath)
                                    : MetadataReference.CreateFromFile(dllPath);
                                references.Add(reference);
                            }
                            catch (Exception ex) when (ex is IOException or BadImageFormatException or UnauthorizedAccessException) { }
                        }
                    }
                }
            }

            return references.ToArray();
        }
        catch (Exception ex) when (ex is IOException or JsonException or UnauthorizedAccessException)
        {
            return Array.Empty<MetadataReference>(); // Graceful degradation for I/O and JSON parse errors
        }
    }
}
