using System.Text.Json;
using Lifeblood.Application.Ports.Infrastructure;
using Lifeblood.Application.Ports.Left;
using Microsoft.CodeAnalysis;

namespace Lifeblood.Adapters.CSharp.Internal;

/// <summary>
/// Resolves NuGet package assemblies from obj/project.assets.json.
/// This file is generated by 'dotnet restore' and maps each package to its compile-time DLLs.
/// Falls back gracefully if the file doesn't exist (pre-restore state).
/// </summary>
internal sealed class NuGetReferenceResolver
{
    private readonly IFileSystem _fs;

    public NuGetReferenceResolver(IFileSystem fs) => _fs = fs;

    /// <summary>
    /// Resolve NuGet references for a module, deduplicating via shared cache.
    /// Without the cache, 100 modules sharing the same NuGet packages create
    /// 100 independent MetadataReference objects per shared DLL.
    /// </summary>
    public MetadataReference[] Resolve(ModuleInfo module, string projectRoot,
        SharedMetadataReferenceCache? cache = null)
    {
        var references = new List<MetadataReference>();
        foreach (var dllPath in ResolveAssemblyPaths(module, projectRoot))
        {
            try
            {
                var reference = cache != null
                    ? cache.GetOrCreate(dllPath)
                    : MetadataReference.CreateFromFile(dllPath);
                references.Add(reference);
            }
            catch (Exception ex) when (ex is IOException or BadImageFormatException or UnauthorizedAccessException) { }
        }
        return references.ToArray();
    }

    /// <summary>
    /// Managed compile DLLs selected by the assets manifest. Workspace identity
    /// fingerprints the resolved path set plus each DLL's contents, so harmless
    /// restore metadata churn does not invalidate the graph while a changed
    /// compile asset cannot pass unnoticed.
    /// </summary>
    public string[] ResolveInputPaths(ModuleInfo module, string projectRoot)
    {
        return ResolveAssemblyPaths(module, projectRoot);
    }

    private string[] ResolveAssemblyPaths(ModuleInfo module, string projectRoot)
    {
        var assetsPath = ResolveAssetsPath(module, projectRoot);
        if (assetsPath == null || !_fs.FileExists(assetsPath))
            return Array.Empty<string>();

        try
        {
            var json = _fs.ReadAllText(assetsPath);
            using var doc = JsonDocument.Parse(json);
            return ResolveAssemblyPaths(doc.RootElement);
        }
        catch (Exception ex) when (ex is IOException or JsonException or UnauthorizedAccessException)
        {
            return Array.Empty<string>();
        }
    }

    private static string? ResolveAssetsPath(ModuleInfo module, string projectRoot)
    {
        if (!module.Properties.TryGetValue("projectFile", out var relCsproj))
            return null;

        var csprojPath = Path.GetFullPath(Path.Combine(projectRoot, relCsproj));
        var objDir = Path.Combine(Path.GetDirectoryName(csprojPath)!, "obj");
        return Path.Combine(objDir, "project.assets.json");
    }

    private string[] ResolveAssemblyPaths(JsonElement root)
    {
        var packageFolders = new List<string>();
        if (root.TryGetProperty("packageFolders", out var folders))
        {
            foreach (var folder in folders.EnumerateObject())
                packageFolders.Add(folder.Name);
        }

        if (packageFolders.Count == 0)
            return Array.Empty<string>();

        if (!root.TryGetProperty("targets", out var targets))
            return Array.Empty<string>();

        JsonElement targetPackages = default;
        foreach (var target in targets.EnumerateObject())
        {
            targetPackages = target.Value;
            break; // Use first target framework
        }

        if (targetPackages.ValueKind != JsonValueKind.Object)
            return Array.Empty<string>();

        var paths = new List<string>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var package in targetPackages.EnumerateObject())
        {
            if (!package.Value.TryGetProperty("compile", out var compileAssets))
                continue;

            var pkgId = package.Name;

            foreach (var asset in compileAssets.EnumerateObject())
            {
                var relativeDll = asset.Name;
                if (relativeDll == "_._") continue;
                if (!relativeDll.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)) continue;

                foreach (var folder in packageFolders)
                {
                    var dllPath = Path.Combine(folder, pkgId.ToLowerInvariant(), relativeDll);
                    if (!seen.Add(dllPath)) continue;

                    if (_fs.FileExists(dllPath) && !BclReferenceLoader.IsNativeDll(dllPath))
                        paths.Add(dllPath);
                }
            }
        }

        return paths.ToArray();
    }
}
