using System.Text;
using Lifeblood.Application.Ports.Right;
using Lifeblood.Domain.Graph;
using Lifeblood.Domain.Results;

namespace Lifeblood.Connectors.ContextPack;

/// <summary>
/// Generates CLAUDE.md / AGENTS.md sections from the semantic graph.
/// Output is structured markdown that an AI agent can use as instruction context.
/// </summary>
public sealed class InstructionFileGenerator : IInstructionFileGenerator
{
    public string Generate(SemanticGraph graph, AnalysisResult analysis)
    {
        var sb = new StringBuilder();

        sb.AppendLine("## Architecture (auto-generated by Lifeblood)");
        sb.AppendLine();

        // Module boundaries
        var modules = graph.Symbols.Where(s => s.Kind == SymbolKind.Module).ToArray();
        if (modules.Length > 0)
        {
            sb.AppendLine("### Modules");
            sb.AppendLine();
            sb.AppendLine("```");
            foreach (var mod in modules)
            {
                var deps = new List<string>();
                foreach (int idx in graph.GetOutgoingEdgeIndexes(mod.Id))
                {
                    if (graph.Edges[idx].Kind == EdgeKind.DependsOn)
                    {
                        var target = graph.GetSymbol(graph.Edges[idx].TargetId);
                        if (target != null) deps.Add(target.Name);
                    }
                }

                string depStr = deps.Count > 0 ? $" → {string.Join(", ", deps)}" : " (pure leaf)";
                sb.AppendLine($"{mod.Name}{depStr}");
            }
            sb.AppendLine("```");
            sb.AppendLine();
        }

        // Dependency rules
        sb.AppendLine("### Dependency Rules");
        sb.AppendLine();

        var pureModules = modules.Where(m =>
        {
            foreach (int idx in graph.GetOutgoingEdgeIndexes(m.Id))
                if (graph.Edges[idx].Kind == EdgeKind.DependsOn) return false;
            return true;
        }).ToArray();

        if (pureModules.Length > 0)
        {
            sb.AppendLine($"Pure modules (zero deps): {string.Join(", ", pureModules.Select(m => m.Name))}");
            sb.AppendLine();
        }

        // Violations
        if (analysis.Violations.Length > 0)
        {
            sb.AppendLine("### Active Violations");
            sb.AppendLine();
            foreach (var v in analysis.Violations.Take(20))
                sb.AppendLine($"- {v.RuleBroken}");
            sb.AppendLine();
        }

        // High-value files
        var couplingById = analysis.Coupling.ToDictionary(c => c.SymbolId, StringComparer.Ordinal);
        var highValue = graph.Symbols
            .Where(s => s.Kind == SymbolKind.File && !string.IsNullOrEmpty(s.FilePath))
            .Select(s =>
            {
                int fanIn = 0;
                foreach (var child in graph.ChildrenOf(s.Id))
                    if (couplingById.TryGetValue(child.Id, out var m)) fanIn += m.FanIn;
                return (file: s, fanIn);
            })
            .Where(x => x.fanIn > 0)
            .OrderByDescending(x => x.fanIn)
            .Take(15)
            .ToArray();

        if (highValue.Length > 0)
        {
            sb.AppendLine("### High-Value Files (most depended upon)");
            sb.AppendLine();
            sb.AppendLine("| File | Fan-In |");
            sb.AppendLine("|------|--------|");
            foreach (var (file, fanIn) in highValue)
                sb.AppendLine($"| `{file.FilePath}` | {fanIn} |");
            sb.AppendLine();
        }

        // Metrics
        sb.AppendLine("### Metrics");
        sb.AppendLine();
        sb.AppendLine($"- Symbols: {graph.Symbols.Length}");
        sb.AppendLine($"- Edges: {graph.Edges.Length}");
        sb.AppendLine($"- Modules: {modules.Length}");
        sb.AppendLine($"- Violations: {analysis.Violations.Length}");
        sb.AppendLine($"- Cycles: {analysis.Cycles.Length}");
        sb.AppendLine();

        return sb.ToString();
    }
}
